<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="Test_function_block" Id="{db30877d-2af4-4c9c-b052-06e3294a70a7}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Test_function_block
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="Test_function_block">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>