<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="UpdateEventTimestampWithSystemTime" Id="{cd29fbff-ccb2-4baa-826b-53a3bf0ec04a}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION UpdateEventTimestampWithSystemTime 
VAR_INPUT
	stEvent: REFERENCE TO ST_Event;
END_VAR
VAR
	fbGETSYSTEMTIME: GETSYSTEMTIME;
	stFileTime: T_FILETIME;
	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[fbGETSYSTEMTIME(timeLoDW =>stFileTime.dwHighDateTime,
	           timeHiDW =>stFileTime.dwLowDateTime);
stEvent.dtTimestamp:= FILETIME_TO_DT(fileTime:=stFileTime);	
			   ]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>